steps:
- name: 'gcr.io/ca-oiso-test/gcloud-zap:latest'
  entrypoint: bash
  args:
    - -c
    - |
      zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.disablekey=true -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true &
      sleep 25
      zap-cli -p 8080 quick-scan -r $_TARGET_URL
      echo "doone quick-scan!!!!!!!!!!!!!"
      google-cloud-sdk/bin/gsutil report.html cp gs://$_STORAGE_BUCKET/ 
      zap-cli report -f html -o /zap/report.html
      google-cloud-sdk/bin/gsutil /zap/report.html cp gs://$_STORAGE_BUCKET/ 
