steps:
- name: 'owasp/zap2docker-stable'
  entrypoint: bash
  args:
    - -c
    - |
      zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.disablekey=true -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true &
      sleep 25
      zap-cli -p 8080 quick-scan -r $_TARGET_URL
      echo "doone quick-scan!!!!!!!!!!!!!"
      zap-cli report -f html -o /zap/report.html
      echo "doone report!!!!!!!!!!!!!"

artifacts:
  objects:
    location: 'gs://$_STORAGE_BUCKET/'
    paths: ['/zap/report.html']