# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sample.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0csample.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x07\n\x05\x45mpty\"\x16\n\x05Query\x12\r\n\x05query\x18\x01 \x01(\t\"%\n\tSomething\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\",\n\nSomethings\x12\x1e\n\nsomethings\x18\x01 \x03(\x0b\x32\n.Something2E\n\x0cGetSomething\x12\x35\n\x03Get\x12\x06.Empty\x1a\n.Something\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/somethingsb\x06proto3')
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=86,
)


_QUERY = _descriptor.Descriptor(
  name='Query',
  full_name='Query',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='Query.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=110,
)


_SOMETHING = _descriptor.Descriptor(
  name='Something',
  full_name='Something',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Something.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='Something.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=149,
)


_SOMETHINGS = _descriptor.Descriptor(
  name='Somethings',
  full_name='Somethings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='somethings', full_name='Somethings.somethings', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=195,
)

_SOMETHINGS.fields_by_name['somethings'].message_type = _SOMETHING
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Query'] = _QUERY
DESCRIPTOR.message_types_by_name['Something'] = _SOMETHING
DESCRIPTOR.message_types_by_name['Somethings'] = _SOMETHINGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'sample_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  ))
_sym_db.RegisterMessage(Empty)

Query = _reflection.GeneratedProtocolMessageType('Query', (_message.Message,), dict(
  DESCRIPTOR = _QUERY,
  __module__ = 'sample_pb2'
  # @@protoc_insertion_point(class_scope:Query)
  ))
_sym_db.RegisterMessage(Query)

Something = _reflection.GeneratedProtocolMessageType('Something', (_message.Message,), dict(
  DESCRIPTOR = _SOMETHING,
  __module__ = 'sample_pb2'
  # @@protoc_insertion_point(class_scope:Something)
  ))
_sym_db.RegisterMessage(Something)

Somethings = _reflection.GeneratedProtocolMessageType('Somethings', (_message.Message,), dict(
  DESCRIPTOR = _SOMETHINGS,
  __module__ = 'sample_pb2'
  # @@protoc_insertion_point(class_scope:Somethings)
  ))
_sym_db.RegisterMessage(Somethings)



_GETSOMETHING = _descriptor.ServiceDescriptor(
  name='GetSomething',
  full_name='GetSomething',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=197,
  serialized_end=266,
  methods=[
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='GetSomething.Get',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_SOMETHING,
    options=_descriptor._ParseOptions(descriptor_pb2.MethodOptions(), _b('\202\323\344\223\002\024\022\022/api/v1/somethings')),
  ),
])
_sym_db.RegisterServiceDescriptor(_GETSOMETHING)

DESCRIPTOR.services_by_name['GetSomething'] = _GETSOMETHING

# @@protoc_insertion_point(module_scope)
